### ISSUE TITLE
Ouput Strings are in German

### ISSUE THREAD

**Issue by 8666** [nobodyMO/node-red-contrib-astrodata#2]
It would be nice if we can send language tag as input to define output language (Horoscope sign etc.).

**Comment by nobodyMO** [comment]
The strings are currently only available in German. I could also add other languages here, but I can only translate the strings for the languages I know. These would be English and French.

**Comment by 8666** [comment]
English is enough.

**Comment by nobodyMO** [comment]
In version 0.0.3 the language can now be set in the settings. This only has an effect on the daily values.
