### ISSUE TITLE
Add capability of using offset date

### ISSUE THREAD

**Issue by karamo** [nobodyMO/node-red-contrib-astrodata#3]
Damit auch Astrodaten von anderen Zeitpunkten als dem aktuellen Zeitpunkt erhalten werden können, ist es erforderlich, die Möglichkeit einer Offset-Zeit angeben zu können.
Wenn dem Input eine msg.offset=TagOffset gesendet wird, dann wird damit der Zeitpunkt der Astrodaten verändert. Dazu sind die folgenden fett dargestellten und mit Kommentar //WZ versehenen Zeilen einzufügen:
für     **function GetSunpositionNode(n)** {
≈Z.628
`
var JD  = JD0 +( d.getUTCHours() + d.getUTCMinutes()/60. + d.getUTCSeconds () /3600.) /24.;
**node.log("input msg.offset: " + msg.offset);  //WZ
if (msg.offset != undefined) { JD = JD + msg.offset; }  //WZ**
node.log ("JD: " + JD);
`
für    **function GetDayValuesNode(n)** {
≈Z.695
`
var JD  = JD0 +( d.getUTCHours() + d.getUTCMinutes()/60. + d.getUTCSeconds () /3600.) /24.;
**node.log("input msg.offset: " + msg.offset);  //WZ
if (msg.offset != undefined) { JD = JD + msg.offset; }  //WZ**
node.log ("JD: " + JD);
`

**Comment by nobodyMO** [comment]
Ist in der neuen Version 0.0.3 integriert.

**Comment by AndreKR** [comment]
Geht das nur für ganze Tage? Ich kann "morgen um diese Uhrzeit" berechnen (was tagsüber ziemlich nutzlos ist), aber "heute abend" klappt nicht, obwohl ich ausgerechnet habe, wie viele Tage (z.B. 0.21345) das an Offset wären.

**Comment by nobodyMO** [comment]
Im Augenblick lässt sich über das Offset nur der Tag verschieben. Dezimalzahlen werden nicht unterstützt. Für einen beliebigen Zeitpunkt wäre der Offset nicht sinnvoll. Da wäre es sinnvoller, den Zeitstempel direkt von außen setzbar zu machen.
